---
- include: ../../generic/tasks/install_packages.yml
  tags:
    - install_packages 
    - build_opencpu_artifact
    - install_opencpu_artifact
- include: ../../R/tasks/configure_R.yml
  tags:
    - configure_R
    - build_opencpu_artifact
    - install_opencpu_artifact  

- include: prebuild.yml
  tags: always

- include: build_opencpu_package.yml
  tags: 
    - build_opencpu_artifact

- include: install_opencpu.yml
  tags:
    - install_opencpu_artifact

- include: configure_sudoers.yml
  tags:
    - configure_sudoers
