---
- name: Create a network interface with private IP and Public IP address
  azure_rm_networkinterface:
    secret: "{{ azure_secret }}"
    tenant: "{{ azure_tenant }}"
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    name: MyDemoNIC
    resource_group: "{{ azure_resource_group_name }}"
    virtual_network_name: "{{ azure_vnet_name }}"
    security_group_name: "{{ azure_default_security_group }}"
    subnet_name: "{{ azure_default_subnet_name }}"
    public_ip_address_name: "{{ azure_default_publicIP_name }}"
