- include: prebuild.yml
  tags:
    - download_kafka
    - install_kafka

- include: ../../generic/tasks/install_packages.yml
  tags:
    - initial_os_proviosion
    - install_packages
    - install_kafka

- include: download_kafka.yml
  tags:
    - download_kafka
    - install_kafka

- include: stop_kafka.yml
  tags:
    - stop_kafka
    - install_kafka

- include: install_kafka.yml
  tags: install_kafka

- include: configure_kafka.yml
  tags:
    - configure_kafka
    - install_kafka

- include: configure_firewalld_kafka.yml
  tags:
    - firewalld_kafka
    - install_kafka
     
- include: start_kafka.yml
  tags:
    - start_kafka
    - install_kafka

- include: configure_systemd_service_kafka.yml
  tags:
    - configure_systemd_kafka

- include: configure_sudoers_kafka.yml
  tags:
    - configure_sudoers_kafka
