- name: Start Kafka
  command: "./{{ kafka_start_script_name }} {{ kafka_start_script_params }}"
  args:
    chdir: "{{ kafka_dir }}/bin/"
  environment:
    JAVA_HOME: "{{ java_dir }}"
    PATH: "{{ lookup('env', 'PATH') }}:{{ java_dir }}/bin"  

- name: Wait for the Kafka listener port to become available
  wait_for:
    port: "{{ listener_port }}"
    delay: 3
    timeout: 30
    sleep: 5
    connect_timeout: 10
