---
regular_user_PS1: "\\[\\033[36m\\]\\t \\[\\033[32m\\]\\u\\[\\033[32m\\]@\\H\\[\\033[94m\\]:\\w\\[\\033[39m\\]\\n\\\\$\\[$(tput sgr0)\\] "
root_user_PS1: "\\[\\033[36m\\]\\t \\[\\e[31m\\]\\u@\\H\\[\\e[94m\\]:\\w\\[\\e[91m\\]\\n\\\\$\\[$(tput sgr0)\\] "

packages_os:
  - epel-release
  - screen
  - htop
  - libselinux-python
  - nmap-ncat

app_dir: /apps
backups_dir: "{{ app_dir }}/backups"
appuser: usertr
from_scratch: False

download_dir: "{{ app_dir }}/downloads"

kafka_repo_url: http://nexus.sandbox.dolv:8081/repository/thirdparty/
kafka_repo_user: anonymous
kafka_repo_pass: changeme
kafka_reponame: thirdparty
kafka_groupId: org.apache
kafka_artifactId: kafka
kafka_version: 0.10.2.0
kafka_extension: tgz

kafka_artifact: "{{ kafka_artifactId }}-{{kafka_version}}.{{ kafka_extension }}"
kafka_url: "{{ kafka_repo_url }}{{ kafka_groupId | replace('.','/') }}/{{ kafka_artifactId }}/{{ kafka_version }}/{{ kafka_artifact }}"

kafka_dir_link: "{{ app_dir }}/kafka"
kafka_dir: "{{ app_dir }}/kafka-{{ kafka_version }}"
kafka_logsDir: "{{ kafka_dir }}/logs"
kafka_confBackup_Dir: "{{ backups_dir }}/kafka_configs"
kafka_confDir: "{{ kafka_dir }}/config"
kafka_serverProperties: "{{ kafka_confDir }}/server.properties"
kafka_log4gProperties: "{{ kafka_confDir }}/log4j.properties"
kafka_producerProperties: "{{ kafka_confDir }}/producer.properties"
kafka_consumerProperties: "{{ kafka_confDir }}/consumer.properties"
kafka_start_script_name: "kafka-server-start.sh"
kafka_start_script_params: "-daemon {{ kafka_serverProperties }}"
kafka_stop_script_name: "kafka-server-stop.sh"

kafka_configs:
  - "{{ kafka_serverProperties }}"
  - "{{ kafka_log4gProperties }}"
  - "{{ kafka_producerProperties }}"
  - "{{ kafka_consumerProperties }}"  

kafka_clustered: False

brokerId: 0
delete_topic_enable: "true"
listener_name: "PLAINTEXT"
kafka_listener_port: 9092
kafka_host_name: ""
kafka_listeners: "{{ listener_name }}://{{ kafka_host_name }}:{{ kafka_listener_port }}"
kafka_advertisedListeners: "{{ kafka_listeners }}"
listener_security_protocol_map: "PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL"
num_network_threads: 3
num_io_threads: 8
socket_send_buffer_bytes: 102400
socket_receive_buffer_bytes: 102400
socket_request_max_bytes: 104857600
log_partitions_per_topic: 1
num_recovery_threads_per_data_dir: 1
log_flush_interval_messages: 10000
log_flush_interval_ms: 1000
log_retention_hours: 168 
log_retention_bytes: 1073741824
log_segment_bytes: 1073741824
log_retention_check_interval_ms: 300000
zookeeper_connection_str: "localhost:2181"
zookeeper_connection_timeout_ms: 6000

kafka_firewalld_zone: internal
kafka_systemd_service_file: /etc/systemd/system/kafka.service
