---
- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ azure_resource_group_name }}"
    location: "{{ azure_default_location }}"
    tags:
      status: testing
      role: demo-web-server
