---
- name: Create a VM with exiting storage account and NIC
  azure_rm_virtualmachine:
    resource_group: "{{ VM_config.resource_group }}"
    name: "{{ VM_config.name }}"
    vm_size: "{{ VM_config.vm_size }}"
    storage_account: "{{ VM_config.storage_account }}"
    admin_username: "{{ VM_config.user }}"
    ssh_password_enabled: False
    ssh_public_keys:
      - path: "/home/{{ VM_config.user }}/.ssh/authorized_keys"
        key_data: "{{ azure_ssh_public_key_string }}"
    network_interfaces: MyDemoNIC 
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.1'
      version: latest
  register: vm_creation_results
  tags: 
    - vm

- name: Register VM public IP address to variable
  set_fact:
    vm_publicIP: "{{ (vm_creation_results | json_query('ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[*].properties.ipConfigurations[*].properties.publicIPAddress.properties.ipAddress'))[0][0] }}" 
  tags:
    - vm

- name: Create inventory file for newly created VM
  templase: 
    src: inventory.j2
    dest: /tmp/myDemoVM/web-server
    mode: 0644
