---
- name: Check if Zookeeper config file exists
  stat:
    path: "{{ zookeeper_confFile }}"
  register: zcfg

- name: Backup Zookeeper config file.
  copy:
    src: "{{ zookeeper_confFile }}"
    dest: "{{ zookeeper_confBackup_Dir }}/{{ zookeeper_confFile.split('/')[-1] }}.{{ ansible_date_time.iso8601_micro }}"
    remote_src: True
  when: zcfg.stat.exists
  become: True
  become_user: "{{ appuser }}"
