---
- include: backup_Zookeeper_config.yml
  when: not from_scratch

- name: Remove Zookeeper folders in order to recreate
  file:
    path: "{{ zookeeper_dir }}/{{ item }}"
    state: absent
  with_items:
    - "bin"
    - "conf"  
    - "contrib"
    - "lib"
    - "recipies"
    - "src"
  when: not from_scratch  
  
- name: Empty zookeeper folder contents
  shell: "rm {{ zookeeper_dir }}/*"
  args: 
    chdir: "{{ zookeeper_dir }}"
  when:
    - not from_scratch  
    - zookeeper_dir | length > 5

- name: Remove zookeeper logs, data & backup folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ zookeeper_dir }}"
    - "{{ zookeeper_logsDir }}"
    - "{{ zookeeper_dataDir }}"  
    - "{{ zookeeper_confBackup_Dir }}"
  when: from_scratch
 
- name: Create Zookeeper folders.
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ zookeeper_dir }}"
    - "{{ backups_dir }}"
    - "{{ zookeeper_logsDir }}"
    - "{{ zookeeper_dataDir }}"  
    - "{{ zookeeper_confBackup_Dir }}"
  when: from_scratch

- name: Unpack Zookeeper artifact.
  unarchive:
    src: "{{ download_dir }}/{{ zookeeper_artifact }}"
    dest: "{{ download_dir }}/"
    remote_src: True
    list_files: yes
  register: unpack_out

- name: "Move zookeeper to the {{ zookeeper_dir }}"
  shell: "{{ item }}"
  args:
    chdir: "{{ download_dir }}"
  with_items:
    - "mv {{ download_dir }}/{{ unpack_out.files[0] }}* {{ zookeeper_dir }}/"
    - "rm -rf {{ download_dir }}/{{ unpack_out.files[0] }}"
  when: zookeeper_dir|length > 5

- name: Create a simlink to the current verion of zookeeper folder
  file:
    src: "{{ zookeeper_dir }}"
    path: "{{ zookeeper_dir_link }}"
    state: link
    force: yes
