---
- name: Remove Zookeeper folder in order to recreate
  file:
    path: "{{ zookeeper_dir }}"
    state: absent
 
- name: Create Zookeeper folders.
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ zookeeper_dir }}"
    - "{{ backups_dir }}"
    - "{{ zookeeper_logsDir }}"
    - "{{ zookeeper_dataDir }}"  
    - "{{ zookeeper_confBackup_Dir }}"

- include: backup_Zookeeper_config.yml

- name: Unpack Zookeeper artifact.
  unarchive:
    src: "{{ download_dir }}/{{ zookeeper_artifact }}"
    dest: "{{ app_dir }}/"
    remote_src: True
    list_files: yes
  register: unpack_out

- name: Create a simlink to the current verion of zookeeper folder
  file:
    src: "{{ zookeeper_dir }}"
    path: "{{ zookeeper_dir_link }}"
    state: link
    force: yes