- include: ../../generic/tasks/configure_bashrc.yml
  tags:
    - initial_os_proviosion
    - configure_bashrc

- include: ../../generic/tasks/configure_sudoers.yml
  tags:
    - initial_os_proviosion
    - configure_sudoers

- include: ../../generic/tasks/install_packages.yml
  tags:
    - initial_os_proviosion
    - install_packages

- include: download_Zookeeper.yml
  tags: download_zookeeper

- include: install_Zookeeper.yml
  tags: install_zookeeper

# - include: configure_Zookeeper.yml
#   tags:
#     - install_zookeeper
#     - configure_zookeeper

