- include: prebuild.yml
  tags:
    - download_zookeeper
    - install_zookeeper

- include: ../../generic/tasks/configure_bashrc.yml
  tags:
    - initial_os_proviosion
    - configure_bashrc

- include: ../../generic/tasks/configure_sudoers.yml
  tags:
    - initial_os_proviosion
    - configure_sudoers

- include: ../../generic/tasks/install_packages.yml
  tags:
    - initial_os_proviosion
    - install_packages_zookeeper

- include: download_Zookeeper.yml
  tags:
    - download_zookeeper
    - install_zookeeper

- include: stop_Zookeeper.yml
  tags:
    - stop_zookeeper
    - install_zookeeper

- include: install_Zookeeper.yml
  tags: install_zookeeper

- include: configure_Zookeeper.yml
  tags:
    - configure_zookeeper
    - install_zookeeper

- include: configure_firewalld_zookeeper.yml
  tags:
    - firewalld_zookeeper
    - install_zookeeper

- include: start_Zookeeper.yml
  tags:
    - start_zookeeper
    - install_zookeeper

- include: configure_systemd_service_Zookeeper.yml
  tags:
    - configure_systemd_zookeeper

- include: configure_sudoers_zookeeper.yml
  tags:
    - configure_sudoers_zookeeper
