- name: Start Zookeeper
  command: "./zkServer.sh start"
  args:
    chdir: "{{ zookeeper_dir }}/bin/"
  environment:
    JAVA_HOME: "{{ java_dir_link }}"
    PATH: "{{ lookup('env', 'PATH') }}:{{ java_dir }}/bin"  

- name: Wait for the Zookeeper clientPort port to become available
  wait_for:
    port: "{{ zookeeper_clientPort }}"
    delay: 10
    timeout: 30
    sleep: 5
    connect_timeout: 10
