---
app_dir: /apps
tools_dir: "{{ app_dir }}/tools"
appuser: usertr

# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
# jenkins_version: "1.644"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: "{{ app_dir }}/jenkins"
jenkins_cert_dir: "{{ jenkins_home }}/ssl"
jenkins_hostname: localhost
jenkins_http_port: 80
jenkins_https_port: 443
jenkins_jar_location: "{{ app_dir }}/jenkins-cli.jar"
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""
jenkins_admin_token: ""
jenkins_admin_token_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"

jenkins_plugins:
  - greenballs
  - active-directory

jenkins_ssl_cert_country_code: "US"
jenkins_ssl_cert_state: "Texas"
jenkins_ssl_cert_locality: "Austin"
jenkins_ssl_cert_org_name: "Newgistics, Inc"
jenkins_ssl_cert_org_unit: "Nethawk Project"
jenkins_ssl_cert_cname: "nhjenkins01.corpdom1.com"
jenkins_ssl_cert_email: "odudchenko@newgistics.com"
jenkins_ssl_cert_duration: 365
jenkins_ssl_cert_altnames:
  - number: 1
    name: "nhjenkins"
  - number: 2
    name: "nhjenkins.corpdom1.com"
  - number: 3
    name: "nhjenkins.newgistics.com"
