---
- hosts: all
  gather_facts: False 
#  gather_facts: True

  tasks:
      - name: debug var
        debug:
                var: "{{item}}"
        with_items:
          -  groups['kafka_cluster']
