---
regular_user_PS1: "\\[\\033[36m\\]\\t \\[\\033[32m\\]\\u\\[\\033[32m\\]@\\H\\[\\033[94m\\]:\\w\\[\\033[39m\\]\\n\\\\$\\[$(tput sgr0)\\] "
root_user_PS1: "\\[\\033[36m\\]\\t \\[\\e[31m\\]\\u@\\H\\[\\e[94m\\]:\\w\\[\\e[91m\\]\\n\\\\$\\[$(tput sgr0)\\] "

packages_os:
  - epel-release
  - screen
  - htop
  - libselinux-python

app_dir: /apps
appuser: usertr

download_dir: "{{ app_dir }}/downloads"

zookeeper_version: 3.4.10
zookeeper_artifact: "zookeeper-{{zookeeper_version}}.tar.gz"
zookeeper_url: "http://www.us.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/{{ zookeeper_artifact }}"


zookeeper_dir_link: "{{ app_dir }}/zookeeper"
zookeeper_dir: "{{ app_dir }}/zookeeper-{{ zookeeper_version }}"

fileshares:
  - remote_share: "//rtrainingmodels.file.core.windows.net/modelshare"
    local_mount_point: "{{ scripts_folder }}/models"
    fstype: "cifs"
    mount_options: "credentials=/home/{{ appuser }}/.cred/modelshare,rw,serverino,vers=3.0,file_mode=0777,dir_mode=0777"
    dump_frequency: 0
    fsck_order: 0
    share_credentials_dst_location: "/home/{{ appuser }}/.cred/modelshare"
    share_credentials_src_location: modelshare
