---
regular_user_PS1: "\\[\\033[36m\\]\\t \\[\\033[32m\\]\\u\\[\\033[32m\\]@\\H\\[\\033[94m\\]:\\w\\[\\033[39m\\]\\n\\\\$\\[$(tput sgr0)\\] "
root_user_PS1: "\\[\\033[36m\\]\\t \\[\\e[31m\\]\\u@\\H\\[\\e[94m\\]:\\w\\[\\e[91m\\]\\n\\\\$\\[$(tput sgr0)\\] "

packages_os:
  - epel-release
  - screen
  - htop
  - libselinux-python

app_dir: /apps
appuser: usertr

download_dir: "{{ app_dir }}/downloads"

zookeeper_repo_url: http://nexus.sandbox.dolv:8081/repository/thirdparty/
zookeeper_repo_user: anonymous
zookeeper_repo_pass: changeme
zookeeper_reponame: thirdparty
zookeeper_groupId: org.apache
zookeeper_artifactId: zookeeper
zookeeper_version: 3.4.10
zookeeper_extension: tar.gz


zookeeper_artifact: "{{ zookeeper_artifactId }}-{{zookeeper_version}}.{{ zookeeper_extension }}"
zookeeper_url: "{{ zookeeper_repo_url }}{{ zookeeper_groupId }}/{{ zookeeper_artifactId }}/{{ zookeeper_version }}/{{ zookeeper_artifact }}"


zookeeper_dir_link: "{{ app_dir }}/zookeeper"
zookeeper_dir: "{{ app_dir }}/zookeeper-{{ zookeeper_version }}"
