---
- name: Ensure dependencies are installed.
  package:
    name:
      - curl
      - libselinux-python
      - initscripts
      - openssl  
    state: installed
  tags:
    - install_packages_jenkins 

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: True
  become_method: sudo
  tags:
    - install_jenkins

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"
  become: True
  become_method: sudo
  tags:
    - install_jenkins

- name: Ensure application folders exists.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
  become: True
  become_method: sudo
  with_items:
    - "{{ app_dir }}"
    - "{{ download_dir }}"
    - "{{ jenkins_home }}"
    - "{{ jenkins_cert_dir }}"  
  tags:
    - create_folders_jenkins


- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    dest: "{{ download_dir }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
  when: jenkins_version is defined
  become: True
  become_user: "{{ appuser }}"
  tags:
    - download_jenkins
    - install_jenkins

- name: Check if we downloaded a specific version of Jenkins.
  stat:
    path: "{{ download_dir }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
  register: specific_version
  when: jenkins_version is defined
  tags:
    - download_jenkins
    - install_jenkins

- name: Install our specific version of Jenkins.
  package:
    name: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    state: installed
  when: jenkins_version is defined and specific_version.stat.exists
  notify: configure default users
  become: True
  become_method: sudo
  tags:
    - install_jenkins

- name: Ensure Jenkins is installed.
  package:
    name: jenkins
    state: "{{ jenkins_package_state }}"
  notify: configure default users
  become: True
  become_method: sudo
  tags:
          - install_jenkins
