---
- name: Ensure application folder exists.
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ appuser }}"
    group: root
  become: True
  become_method: sudo

- name: Ensure Download folder exists.
  file:
    path: "{{ download_dir }}"
    state: directory
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
  become:  
  become_method: su 
  
- name: Download Java
  get_url:
    url: "{{ java_url }}"
    dest: "{{ download_dir }}/{{ java_artifact }}"
    owner: "{{ appuser }}"
    mode: 0774
    url_username: "{{ java_repo_user }}"
    url_password: "{{ java_repo_pass}}"

