- include: ../../generic/tasks/configure_bashrc.yml
  tags:
    - initial_os_proviosion
    - configure_bashrc

- include: ../../generic/tasks/configure_sudoers.yml
  tags:
    - initial_os_proviosion
    - configure_sudoers

- include: ../../generic/tasks/install_packages.yml
  tags:
    - initial_os_proviosion
    - install_packages

- include: download_java.yml
  tags: 
    - download_java
    - install_java

- include: install_java.yml
  tags: install_java

# - include: configure_java.yml
#   tags:
#     - install_java
#     - configure_java

